version: '2'
services:
  ork3app:
    build:
      context: ./
      dockerfile: Dockerfile.nginx-php8
    ports:
      - 19080:80
    working_dir: /var/www
    volumes:
      - .:/var/www/ork.amtgard.com
    env_file: .dev.env
    environment:
      - ENVIRONMENT=DEV
    container_name: ork3-php8-app
    networks:
      - ork3-php8-net
  ork3db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: 'ork'
      # So you don't have to use root, but you can if you like
      MARIADB_USER: 'ork'
      # You can use whatever password you like
      MARIADB_PASSWORD: 'secret'
      # Password for root access
      MARIADB_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '19306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data-db:/var/lib/mysql
    container_name: ork3-php8-db
    networks:
      - ork3-php8-net

volumes:
  data-db: {}

networks:
  ork3-php8-net:
